name: Build

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: gdlint .
  Godot:
    runs-on: ubuntu-latest
    needs: [Lint]
    strategy:
      matrix:
        platform: [Web]
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Build
        id: build
        uses: manleydev/build-godot-action@v1.5.0
        with:
          name: index
          preset: ${{ matrix.platform }}
          debugMode: "true"
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Client - ${{ matrix.platform }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
